### ISSUE TITLE
Feature: Flexible Basename Folder For phpwax

### ISSUE THREAD

**Issue by sheldon** [phpwax/phpwax#1]
At the moment wax needs to be in a folder called wax and it needs to be either in the root of the user or in the pear folder. While these work fine for us, someone new to the project would be confused by this since cloning the git repo gives a phpwax folder instead of a wax folder.

Shall we add phpwax to the possible search path?

**Comment by sheldon** [comment]
charles did this... apparently. lets see.

**Comment by charlesmarshall** [comment]
is on new-cache branch..
