### ISSUE TITLE
WaxForm on exisiting models doesnt update from posted data

### ISSUE THREAD

**Issue by charlesmarshall** [phpwax/phpwax#17]
$form = new WaxForm(new CmsContent($id));
if($saved = $form->save()) $this->redirect_to("/thanks");

This always returns true, as the save call always uses the data from the model without checking the post.. so if your post data is invalid it doesnt get saved.. Have to do this instead:

$example_model = new model_class($id);  
if($model = $example_model->handle_post()) $this->redirect_to("/thanks");
$form = new WaxForm($example_model);

**Comment by oneblackbear** [comment]
I just checked in a fix. What I think it was is there was a check on the post data to see if it existed then it handed post data to the model. If it returned false it never got passed. I've changed it so it does an isset check instead. 

Tested with this code:
    $this->form = new WaxForm(new Feature(6));
    if($this->form->save()) die("You're valid");

**Comment by rossriley** [comment]
Marked closed for now if this still isn't working reopen.
