### ISSUE TITLE
BUG: CheckboxInput Widget not setting hidden value

### ISSUE THREAD

**Issue by joeturner** [phpwax/phpwax#19]
When using the CheckboxInput Widget as expected a hidden field is created ahead of the input field. Reason for this is so a value is always posted, whether the checkbox is selected or not.

At the moment, the hidden field is being rendered correctly, but the value isn't being set at all, just leaves value="". An $unchecked_value is present in the widget, and is being passed through to the HiddenInput constructor.

**Comment by charlesmarshall** [comment]
I think you can set unchecked_value on the field definition in your model in side the options array at the end (3 param) however I think this might be more due to the Request class only checking $_REQUEST[$name] and not using isset() ... will look in to this when have time

**Comment by oneblackbear** [comment]
I think this one is squashed now value is definitely setting to zero by default. So if you want it to trigger a required validation setting it back to empty will do the job...

```
$el->render(array("unchecked_value"=>"");
```
