### ISSUE TITLE
Validation of unique values on Models is letting anything through.

### ISSUE THREAD

**Issue by joeturner** [phpwax/phpwax#24]
Appears to be all on field types...

$this->define("email_address", "EmailField", array('maxlength'=>255, 'required'=>true, "unique"=>true) );

and saving the form with

$this->newsletter_form = new WaxForm($newsletter);
    if($this->newsletter_form->save()) { ... }

allows multiple insertions of the same email address.

**Comment by charlesmarshall** [comment]
yeah.. doesnt seem to be a valid unique function that gets called any more ... will have a dig around and check

**Comment by charlesmarshall** [comment]
that should be sorted now.. done a push .. have a play
