### ISSUE TITLE
filters for many to many

### ISSUE THREAD

**Issue by sheldon** [phpwax/phpwax#27]
seems the filters are being added incorrectly for manytomany fields. the value for the in operator is an array of rows instead of an array of ids.

see TestWaxModelField.php line 162. the final all call there returns the model with filters set incorrectly. like:

```
        [filters] => Array
            (
                [0] => Array
                    (
                        [name] => id
                        [operator] => in
                        [value] => Array
                            (
                                [0] => Array
                                    (
                                        [id] => 1
                                        [name] => Property 1
                                    )

                                [1] => Array
                                    (
                                        [id] => 2
                                        [name] => Property 2
                                    )

                            )

                    )

                [name] => Array
                    (
                        [name] => name
                        [operator] => =
                        [value] => Property 2
                    )

            )
```

**Comment by charlesmarshall** [comment]
will have a look at this ... another strange filtering one..  whats the code used to create this?

**Comment by charlesmarshall** [comment]
ignore me.. didnt read that bit of the post

**Comment by charlesmarshall** [comment]
strange... ive set up a test example and had no errors... will setup the framework tests and see if can repeat it..

**Comment by charlesmarshall** [comment]
this was only happening for eager loaded items due to how the many to many fields __call was passing along filters. I have modified this, testing locally before pushing.

**Comment by charlesmarshall** [comment]
seems fixed, pushed
