### ISSUE TITLE
New filter layout does not support overwrites

### ISSUE THREAD

**Issue by charlesmarshall** [phpwax/phpwax#3]
The new method of calling filters("col_name", "value", "operator") does not support overwriting of cols ... so passing in filter("x", y) then filter("x", z) will return 0 results as the array is incremental and not key based. 

This means doing it this way requires a call to clear and resetting group if its been used then reapplying any other filters you want back on the object, making for very ugly code.

**Comment by sheldon** [comment]
fixed. the overwrites will happen on any = operation (which is the default). if you want OR-based queries you have to do them raw anyway, and then overwrites don't happen. best of both worlds ftw.
